# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='address',
            name='seller',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='shop_owner_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
